# -*- coding: utf-8 -*-
{
    'name': 'SICA - Member Management System',
    'version': '1.0',
    'category': 'Hidden',
    'summary': 'SICA - Member Management System',
    'description': 'SICA - Member Management System',
    'author': 'Sakkthi V A',
    'depends': ['web', 'mail'],
    'data': [
        'data/sequence_data.xml',
        'data/data.xml',
        'security/ir.model.access.csv',
        'views/res_member_view.xml',
        'views/sica_cbt_receipt_view.xml',
        'views/other_receipt_view.xml',
        "views/expense_view.xml",
        "views/movie_list.xml",
        'views/excel_upload_wizard_view.xml',
        "views/cash_deposit_view.xml",
        "views/cash_withdraw_view.xml",
        "views/reports_view.xml",
        "wizard/profit_loss_report_view.xml",
        "report/member_details_report_templates.xml",
        "report/sica_cbt_report_templates.xml",
        "report/voucher_report_templates.xml",
        "report/other_receipt_report_templates.xml",
        "report/sica_cbt_report.xml",
        "report/voucher_report.xml",
        "report/other_receipt_report.xml",
        "report/member_details_report.xml",
        'views/menuitems.xml',
        'views/expense_type.xml',
        'views/member_payment_request.xml',
        'views/member_payment.xml',
        'views/medium.xml',
        'views/member_job_seeker.xml',
        'views/member_job_provider.xml',
        'views/member_skill.xml',
        'views/discussion_forum.xml',
        'views/grievance.xml',
        'views/shooting.xml',
        'views/mobile_photo.xml',
        'views/shooting_event.xml',
        'views/spd.xml',
        'views/gallery.xml',
        'views/tech_talk.xml',
        'views/news.xml',
        'views/blog.xml',
        'views/mmme.xml',
        'views/support.xml',
        'views/res_configuration.xml',
        'views/push_notification.xml'
    ],
    'assets': {
        'web.assets_backend': [
            'member_management_system/static/src/css/avatar_image.css'
        ]
    },
    'auto_install': False,
    'installable': True,
    'application': True,
}
